from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class BusinessArea:
    name: str
    description: str
    keywords: tuple[str, ...]


COMPANY_NAME = "Third Horizon"

BUSINESS_AREAS: tuple[BusinessArea, ...] = (
    BusinessArea(
        name="Policy and regulatory advisory",
        description="Work tied to federal/state health policy, reimbursement rules, Medicaid, Medicare, and compliance strategy.",
        keywords=(
            "aca",
            "aco",
            "administration",
            "advance notice",
            "agency",
            "benchmark",
            "benefit",
            "budget",
            "cbo",
            "medicaid",
            "medicare",
            "medicare advantage",
            "medicare part d",
            "dual eligible",
            "managed care",
            "cms",
            "cmmi",
            "hhs",
            "fda",
            "nih",
            "omb",
            "congress",
            "senate",
            "house",
            "state",
            "federal",
            "legislation",
            "lawmakers",
            "regulation",
            "regulatory",
            "policy",
            "rulemaking",
            "proposed rule",
            "final rule",
            "guidance",
            "enforcement",
            "audit",
            "oversight",
            "reimbursement",
            "payment",
            "fee schedule",
            "coding",
            "hcpcs",
            "cpt",
            "risk adjustment",
            "star ratings",
            "quality bonus",
            "risk corridor",
            "rate",
            "rate notice",
            "rate cut",
            "rebate",
            "drug pricing",
            "price negotiation",
            "rule",
            "compliance",
            "waiver",
            "1115 waiver",
            "section 1115",
            "demonstration",
            "prior authorization",
            "network adequacy",
            "access standard",
            "parity",
            "no surprises act",
            "hipaa",
        ),
    ),
    BusinessArea(
        name="Payer and provider strategy",
        description="Advisory work for health plans, provider organizations, networks, and market positioning.",
        keywords=(
            "aco",
            "ambulatory",
            "anthem",
            "benefit design",
            "blue cross",
            "blue shield",
            "caremark",
            "channel",
            "clinic",
            "cigna",
            "cvs",
            "elevance",
            "employer",
            "group health",
            "health plan",
            "health system",
            "hospital",
            "humana",
            "payer",
            "provider",
            "provider group",
            "physician",
            "practice",
            "insurance",
            "insurer",
            "ma plan",
            "medicaid plan",
            "member",
            "membership",
            "molina",
            "network",
            "network adequacy",
            "optum",
            "pharmacy benefit manager",
            "pbm",
            "provider sponsored",
            "referral",
            "site of care",
            "unitedhealth",
            "unitedhealthcare",
            "centene",
            "contract",
            "contracting",
            "rate negotiation",
            "delegation",
            "delegated risk",
            "capitation",
            "medical loss ratio",
            "mlr",
            "claims",
            "utilization management",
            "care navigation",
            "narrow network",
            "value-based contract",
        ),
    ),
    BusinessArea(
        name="Value-based care and transformation",
        description="Programs connected to risk contracts, care delivery redesign, outcomes, affordability, and quality.",
        keywords=(
            "value-based",
            "value based",
            "vbc",
            "risk",
            "risk contract",
            "shared savings",
            "bundled payment",
            "episode",
            "total cost of care",
            "tcoc",
            "outcomes",
            "quality measure",
            "hedis",
            "stars",
            "quality",
            "affordability",
            "care management",
            "case management",
            "disease management",
            "population health",
            "health equity",
            "social determinants",
            "sdoh",
            "utilization",
            "utilization review",
            "prior authorization",
            "primary care",
            "primary care transformation",
            "behavioral health",
            "integrated care",
            "whole person care",
            "care coordination",
            "care delivery",
            "clinical model",
            "digital health",
            "remote monitoring",
            "telehealth",
            "virtual care",
            "home health",
            "hospital at home",
            "post-acute",
            "readmission",
            "patient experience",
            "access",
            "workforce",
            "burnout",
        ),
    ),
    BusinessArea(
        name="Market intelligence and growth",
        description="Competitive intelligence, M&A monitoring, go-to-market planning, and opportunity sizing.",
        keywords=(
            "acquisition",
            "merger",
            "m&a",
            "joint venture",
            "divestiture",
            "spin off",
            "ipo",
            "private equity",
            "venture",
            "investment",
            "funding",
            "financing",
            "valuation",
            "deal",
            "partnership",
            "alliance",
            "expansion",
            "launch",
            "commercialization",
            "growth",
            "market",
            "market share",
            "market access",
            "addressable market",
            "tam",
            "competition",
            "competitor",
            "rival",
            "benchmark",
            "positioning",
            "forecast",
            "guidance",
            "earnings",
            "revenue",
            "margin",
            "profit",
            "profitability",
            "ebitda",
            "cash flow",
            "debt",
            "downgrade",
            "upgrade",
            "analyst",
            "stock",
            "shares",
            "investor",
            "dividend",
            "buyback",
            "pipeline",
            "patent",
            "biosimilar",
            "generic",
            "launch",
            "approval",
            "clinical trial",
            "phase 1",
            "phase 2",
            "phase 3",
            "supply",
            "shortage",
        ),
    ),
    BusinessArea(
        name="Client reputation and strategic communications",
        description="Messaging and stakeholder strategy when controversy, lawsuits, cyber incidents, or access issues hit clients.",
        keywords=(
            "lawsuit",
            "litigation",
            "settlement",
            "court",
            "attorney general",
            "doj",
            "ftc",
            "oig",
            "investigation",
            "probe",
            "fraud",
            "false claims",
            "kickback",
            "whistleblower",
            "subpoena",
            "consent decree",
            "sanction",
            "penalty",
            "fine",
            "breach",
            "cyber",
            "cybersecurity",
            "ransomware",
            "hack",
            "privacy",
            "data security",
            "data leak",
            "phishing",
            "outage",
            "disruption",
            "shutdown",
            "strike",
            "labor",
            "union",
            "controversy",
            "criticism",
            "backlash",
            "scrutiny",
            "complaint",
            "allegation",
            "misconduct",
            "patient harm",
            "patient safety",
            "recall",
            "quality issue",
            "adverse event",
            "warning letter",
            "fda warning",
            "product liability",
            "access issue",
            "denial",
            "delayed care",
            "media",
            "reputation",
        ),
    ),
)
